apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-pipelinerun-
  annotations:
    "appstudio.redhat.com/updateComponentOnSuccess": "false"
    pipelinesascode.tekton.dev/repo-url: 'https://github.com/dheerajodha/devfile-sample-go-basic' 
                                                                               # ←needs update
    pipelinesascode.tekton.dev/sha-title: yolo                                 # ←needs update
    pipelinesascode.tekton.dev/pull-request: '110'                             # ←needs update
    pipelinesascode.tekton.dev/sha-url: https://github.com/dheerajodha/devfile-sample-go-basic/pull/110/commits/26e2b20139779e5399422ac41800ba533d82927c                                                                 # ←needs update
    pipelinesascode.tekton.dev/installation-id: '43370331'                     # ←needs update
    chains.tekton.dev/signed: "true"
  labels:
    pipelines.appstudio.openshift.io/type: "build"
    pipelines.openshift.io/used-by: "build-cloud"
    pipelines.openshift.io/runtime: "nodejs"
    pipelines.openshift.io/strategy: "s2i"
    appstudio.openshift.io/component: "component-sample"                       # ←needs update
    pipelinesascode.tekton.dev/event-type: pull_request
    pipelinesascode.tekton.dev/state: completed
    pipelinesascode.tekton.dev/sender: dheerajodha                             # ←needs update
    pipelinesascode.tekton.dev/branch: main
    pipelinesascode.tekton.dev/url-org: dheerajodha                            # ←needs update
    pipelinesascode.tekton.dev/url-repository: devfile-sample-go-basic         # ←needs update
    pipelinesascode.tekton.dev/sha: 26e2b20139779e5399422ac41800ba533d82927c   # ←needs update
    pipelinesascode.tekton.dev/git-provider: github
spec:
  pipelineRef:
    name: build-pipeline-pass
    bundle: quay.io/redhat-appstudio/example-tekton-bundle:build-pipeline-pass
  params:
    - name: output-image
      value: "quay.io/redhat-appstudio/sample-image"
    - name: image-digest
      value: "sha256:98f7c02fc24f9a66a39660ecae95bf0e84660e62281d98d660cb4517ad69c17b"

